### ISSUE TITLE
vertical interpolation doesn't work

### ISSUE THREAD

**Issue by clearsky112** [barronh/aqmbc#2]
Hello,

   I tried to map GC outputs (lev=72) to the CMAQ BCON format. But the output is still "LAY 72". I used _vglvls as the default setting in bcon.py.
  The command I used shown as below:
python bcon.py -O  --expr ../definitions/gc/gcnc_airmolden.expr --expr ../definitions/gc/gc12_to_ae6_nvPOA.expr  --interp linear --format gcnc --grid TEST ../CONC/GCHP.SpeciesConc.20180701_0330z.nc4 GCHP.SpeciesConc.20180701_0330z.nc4.BCON.nc

   Could you help me about this problem? Thanks in advance.

**Comment by barronh** [comment]
This is a problem with pseudonetcdf that has been addressed, but not yet released. See https://github.com/barronh/pseudonetcdf/issues/90. You can solve it by installing the fixed branch or the live code version.  A new release has not been issued, so you have to install from the source.

Below is an installation command that will install from the live code. Since you have already installed pseudonetcdf, you may need to uninstall it or force the reinstall. If you're installing just for your self, add the `--user` option.

```
python -m pip uninstall pseudonetcdf
python -m pip install https://github.com/barronh/pseudonetcdf/archive/refs/heads/master.zip
```

**Comment by clearsky112** [comment]
> This is a problem with pseudonetcdf that has been addressed, but not yet released. See [barronh/pseudonetcdf#90](https://github.com/barronh/pseudonetcdf/issues/90). You can solve it by installing the fixed branch or the live code version. A new release has not been issued, so you have to install from the source.
> 
> Below is an installation command that will install from the live code. Since you have already installed pseudonetcdf, you may need to uninstall it or force the reinstall. If you're installing just for your self, add the `--user` option.
> 
> ```
> python -m pip uninstall pseudonetcdf
> python -m pip install https://github.com/barronh/pseudonetcdf/archive/refs/heads/master.zip
> ```

Thank you very much. It worked well.
